import argparse
from datetime import datetime
from pathlib import Path
from polygon_checker import is_land
from navigation import find_sea_route

def create_kml(waypoints, start_name="Start", end_name="End", output_file="route.kml"):
    """
    웨이포인트로부터 KML 파일을 생성합니다.
    
    :param waypoints: [(lat, lon), ...] 형식의 좌표 리스트
    :param start_name: 출발지 이름
    :param end_name: 목적지 이름
    :param output_file: 출력 파일 경로
    :return: 생성된 파일 경로
    """
    kml_header = '''<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Maritime Route</name>
    <description>Generated by Land-Sea Checker</description>
    
    <!-- 경로 스타일 -->
    <Style id="routeStyle">
      <LineStyle>
        <color>ff0000ff</color>
        <width>3</width>
      </LineStyle>
    </Style>
    
    <!-- 시작점 스타일 -->
    <Style id="startStyle">
      <IconStyle>
        <color>ff00ff00</color>
        <scale>1.2</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/grn-circle.png</href>
        </Icon>
      </IconStyle>
    </Style>
    
    <!-- 종료점 스타일 -->
    <Style id="endStyle">
      <IconStyle>
        <color>ff0000ff</color>
        <scale>1.2</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/red-circle.png</href>
        </Icon>
      </IconStyle>
    </Style>
'''

    kml_footer = '''  </Document>
</kml>
'''
    
    # 시작점 마커
    start_placemark = f'''    <Placemark>
      <name>{start_name}</name>
      <description>Starting Point</description>
      <styleUrl>#startStyle</styleUrl>
      <Point>
        <coordinates>{waypoints[0][1]:.6f},{waypoints[0][0]:.6f},0</coordinates>
      </Point>
    </Placemark>
'''
    
    # 종료점 마커
    end_placemark = f'''    <Placemark>
      <name>{end_name}</name>
      <description>Destination Point</description>
      <styleUrl>#endStyle</styleUrl>
      <Point>
        <coordinates>{waypoints[-1][1]:.6f},{waypoints[-1][0]:.6f},0</coordinates>
      </Point>
    </Placemark>
'''
    
    # 경로 라인
    coordinates_str = '\n          '.join(
        f'{lon:.6f},{lat:.6f},0' for lat, lon in waypoints
    )
    
    route_placemark = f'''    <Placemark>
      <name>Sea Route</name>
      <description>Maritime navigation route with {len(waypoints)} waypoints</description>
      <styleUrl>#routeStyle</styleUrl>
      <LineString>
        <tessellate>1</tessellate>
        <coordinates>
          {coordinates_str}
        </coordinates>
      </LineString>
    </Placemark>
'''
    
    # KML 파일 작성
    kml_content = kml_header + start_placemark + end_placemark + route_placemark + kml_footer
    
    output_path = Path(output_file)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(kml_content)
    
    return str(output_path.absolute())

def main():
    parser = argparse.ArgumentParser(description='Maritime navigation tools using OSM land polygons.')
    subparsers = parser.add_subparsers(dest='command', help='Available commands')
    
    # check 명령어: 좌표가 육지인지 바다인지 확인
    check_parser = subparsers.add_parser('check', help='Check if a coordinate is on land or sea')
    check_parser.add_argument('latitude', type=float, help='Latitude of the coordinate')
    check_parser.add_argument('longitude', type=float, help='Longitude of the coordinate')
    
    # route 명령어: 두 점 사이의 해상 경로 계산
    route_parser = subparsers.add_parser('route', help='Calculate sea route between two points')
    route_parser.add_argument('start_lat', type=float, help='Start latitude')
    route_parser.add_argument('start_lon', type=float, help='Start longitude')
    route_parser.add_argument('end_lat', type=float, help='End latitude')
    route_parser.add_argument('end_lon', type=float, help='End longitude')
    route_parser.add_argument('--step', type=float, default=10.0, help='Step size in km (default: 10)')
    route_parser.add_argument('--clearance', type=float, default=10.0, 
                            help='Minimum distance from coastline in km (default: 10)')
    route_parser.add_argument('--max-iter', type=int, default=1000, 
                            help='Maximum iterations (default: 1000)')
    route_parser.add_argument('--output', type=str, default=None,
                            help='Output KML file path (default: route_YYYYMMDD_HHMMSS.kml)')
    
    args = parser.parse_args()

    try:
        if args.command == 'check':
            # 육지/바다 확인
            if is_land(args.latitude, args.longitude):
                print("The coordinate is on land.")
            else:
                print("The coordinate is in the sea.")
        
        elif args.command == 'route':
            # 해상 경로 계산
            print(f"Calculating sea route from ({args.start_lat}, {args.start_lon}) "
                  f"to ({args.end_lat}, {args.end_lon})\n")
            
            result = find_sea_route(
                args.start_lat, args.start_lon,
                args.end_lat, args.end_lon,
                step_km=args.step,
                min_clearance_km=args.clearance,
                max_iterations=args.max_iter
            )
            
            if result.get('success'):
                print(f"\n{'='*50}")
                print(f"ROUTE CALCULATION SUCCESS")
                print(f"{'='*50}")
                print(f"Direct distance: {result['direct_distance']:.2f} km")
                print(f"Route distance: {result['total_distance']:.2f} km")
                print(f"Efficiency: {result['efficiency']:.1f}%")
                print(f"Number of waypoints: {len(result['waypoints'])}")
                print(f"Iterations: {result['iterations']}")
                
                print(f"\nFirst 5 waypoints:")
                for i, (lat, lon) in enumerate(result['waypoints'][:5], 1):
                    print(f"  {i}. ({lat:.6f}, {lon:.6f})")
                
                if len(result['waypoints']) > 5:
                    print(f"  ...")
                    lat, lon = result['waypoints'][-1]
                    print(f"  {len(result['waypoints'])}. ({lat:.6f}, {lon:.6f})")
                
                # KML 파일 생성
                if args.output:
                    kml_file = args.output
                else:
                    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                    kml_file = f"route_{timestamp}.kml"
                
                start_name = f"Start ({args.start_lat:.4f}, {args.start_lon:.4f})"
                end_name = f"End ({args.end_lat:.4f}, {args.end_lon:.4f})"
                
                kml_path = create_kml(
                    result['waypoints'],
                    start_name=start_name,
                    end_name=end_name,
                    output_file=kml_file
                )
                
                print(f"\n✓ KML file created: {kml_path}")
            else:
                print(f"\n{'='*50}")
                print(f"ROUTE CALCULATION FAILED")
                print(f"{'='*50}")
                print(f"Error: {result.get('error', 'Unknown error')}")
                print(f"Iterations: {result.get('iterations', 0)}")
        
        else:
            parser.print_help()
                
    except Exception as e:
        print(f"An error occurred: {e}")
        import traceback
        traceback.print_exc()

if __name__ == '__main__':
    main()